### PR TITLE
Use a CI for ansiblecube

### PR DESCRIPTION
**Pull request by bochecha**
In addition to plugging us to the CI, this commit also introduces a test, asking ansible to verify the syntax for all of our roles.

### CODE REVIEW

**Comment by bochecha** [comment]
We should add a test to verify that the `*.fact` files are valid JSON.

**Comment by bochecha** [comment]
So I've rebased this branch, and added a few checks:
- all the `*.fact` files are now checked to make sure they are valid JSON
- all the `*.j2` files are now checked to make sure they are valid Jinja2 templates

I'm not entirely sure about the latter, but it seems to work and correctly report the obviously broken templates I've tried.

All tests pass right now because the whole repo is clean (kudos!). Merging this will help ensuring that the repo keeps clean. :smiley:

**Comment by fheslouin** [comment]
Great ! Thank for your help. Nothing else to merge ?

**Comment by bochecha** [comment]
> Nothing else to merge ? 

This should be good to merge right now.

I have some more checks I'm working on, but they aren't ready to be merged yet, so I'll submit them in a future pull request.

**Pull request merged**
