### PR TITLE
Stop kalite nicely and the hard way

### PR DESCRIPTION
**Pull request by fheslouin**
Most of the time Kalite does not want to stop properly for an unknown reason. So if it does not work get the PID and kille the process

### CODE REVIEW

**Comment by fheslouin** [comment]
> Is kill enough though?
> Wouldn't a kill -9 safer?

I did try with a simple `kill` and that was enough. The branch is currently running to check everything is correct !

**Comment by bochecha** [comment]
You could drop all that if you used a systemd unit for kalite.

Then, `systemctl stop kalite` would first try to stop it correctly, and after a (configurable) timeout, it would kill it with the SIGKILL (-9) signal.

**Comment by bochecha** [comment]
```
...
[Service]
Type=forking  # I assume that's what it is, but I'm not sure, do check
ExectStart=/home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py start
ExecStop=/home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py stop
TimeoutStopSec=90  # That's the default
...
```

**Comment by fheslouin** [comment]
@bochecha that's a good one ! :)
I forgot the use of the systemd unit as the playbook evolved...I have to find out the right `Type` as Kalite has to be started in `foreground` otherwise I get some strange behavior.

@swbsf Yes it is quite long, The time for the service to stop, but mainly the latter was always going in timeout... I try to solve this with systemd

**Comment by bochecha** [comment]
> I have to find out the right Type as Kalite has to be started in foreground otherwise I get some strange behavior.

If it's started in the foreground, then you most likely want `Type=simple`, which is the default, and thus you don't need to specify `type` at all.

**Comment by fheslouin** [comment]
Yes I left `Type` to the default option. It worked well as it is. 

We have now to give some test

**Comment by fheslouin** [comment]
Conclusive tests. Merging...

**Pull request merged**
