### PR TITLE
Kalite fix

### LINKED ISSUE #154: Kalite installation fails
Since a few days, kalite installation fails : 

```
TASK [kalite : Install Ka-lite] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/home/ideascube/.kalite/env/bin/pip2 install ka-lite==0.16.9", "failed": true, "msg": "stdout: Downloading/unpacking ka-lite==0.16.9\n  Running setup.py (path:/tmp/pip-build-wGKL0G/ka-lite/setup.py) egg_info for package ka-lite\n    Already blocking...\n    Already blocking...\n    \n    warning: no previously-included files matching '*' found under directory 'kalite/database'\n    warning: no previously-included files matching '*' found under directory 'kalite/static'\n    warning: no previously-included files matching '*' found under directory 'data/khan'\n    warning: no previously-included files matching '*pyc' found under directory 'python-packages'\n    warning: no files found matching '*' under directory 'dist-packages'\nDownloading/unpacking docopt>=0.6,<0.7 (from ka-lite==0.16.9)\n  Downloading docopt-0.6.2.tar.gz\n  Running setup.py (path:/tmp/pip-build-wGKL0G/docopt/setup.py) egg_info for package docopt\n    \nDownloading/unpacking South==0.8.4 (from ka-lite==0.16.9)\nDownloading/unpacking django-js-reverse==0.5.0 (from ka-lite==0.16.9)\n  Downloading django_js_reverse-0.5.0-py2.py3-none-any.whl\nDownloading/unpacking ply==3.4 (from ka-lite==0.16.9)\n  Running setup.py (path:/tmp/pip-build-wGKL0G/ply/setup.py) egg_info for package ply\n    \nDownloading/unpacking slimit==0.8.1 (from ka-lite==0.16.9)\n  Running setup.py (path:/tmp/pip-build-wGKL0G/slimit/setup.py) egg_info for package slimit\n    \nDownloading/unpacking six==1.9.0 (from ka-lite==0.16.9)\n  Downloading six-1.9.0-py2.py3-none-any.whl\nDownloading/unpacking django-appconf==1.0.1 (from ka-lite==0.16.9)\n  Downloading django_appconf-1.0.1-py2.py3-none-any.whl\nDownloading/unpacking peewee==2.6.4 (from ka-lite==0.16.9)\n  Running setup.py (path:/tmp/pip-build-wGKL0G/peewee/setup.py) egg_info for package peewee\n    \nDownloading/unpacking python-dateutil==2.4.2 (from ka-lite==0.16.9)\nDownloading/unpacking django-dbbackup==2.3.2 (from ka-lite==0.16.9)\n  Downloading django-dbbackup-2.3.2.tar.gz\n  Running setup.py (path:/tmp/pip-build-wGKL0G/django-dbbackup/setup.py) egg_info for package django-dbbackup\n    \nDownloading/unpacking ifcfg==0.9.3 (from ka-lite==0.16.9)\n  Downloading ifcfg-0.9.3-py2-none-any.whl\nDownloading/unpacking requests==1.1.0 (from ka-lite==0.16.9)\n  Running setup.py (path:/tmp/pip-build-wGKL0G/requests/setup.py) egg_info for package requests\n    \nDownloading/unpacking Django>=1.5 (from django-js-reverse==0.5.0->ka-lite==0.16.9)\n  Running setup.py (path:/tmp/pip-build-wGKL0G/Django/setup.py) egg_info for package Django\n    Traceback (most recent call last):\n      File \"<string>\", line 17, in <module>\n      File \"/tmp/pip-build-wGKL0G/Django/setup.py\", line 32, in <module>\n        version = __import__('django').get_version()\n      File \"django/__init__.py\", line 1, in <module>\n        from django.utils.version import get_version\n      File \"django/utils/version.py\", line 61, in <module>\n        @functools.lru_cache()\n    AttributeError: 'module' object has no attribute 'lru_cache'\n    Complete output from command python setup.py egg_info:\n    Traceback (most recent call last):\n\n  File \"<string>\", line 17, in <module>\n\n  File \"/tmp/pip-build-wGKL0G/Django/setup.py\", line 32, in <module>\n\n    version = __import__('django').get_version()\n\n  File \"django/__init__.py\", line 1, in <module>\n\n    from django.utils.version import get_version\n\n  File \"django/utils/version.py\", line 61, in <module>\n\n    @functools.lru_cache()\n\nAttributeError: 'module' object has no attribute 'lru_cache'\n\n----------------------------------------\nCleaning up...\nCommand python setup.py egg_info failed with error code 1 in /tmp/pip-build-wGKL0G/Django\nStoring debug log for failure in /root/.pip/pip.log\n"}
```
This is linked to newly released version 2.0 of django which get installed by default, but is generating this error.
Django installed version should be <2.0

### PR DESCRIPTION
**Pull request by swbsf**
Fixes #154 .

While avoiding force-upgrade of django on already installed devices.

### CODE REVIEW

**Comment by fheslouin** [comment]
`requirements.txt` says Django 1.5.12 https://github.com/learningequality/ka-lite/blob/master/requirements.txt#L9

I don't know how it can install Django 2....

**Comment by swbsf** [comment]
True, but : 
```
(env)idb-bsf-vagrant-269 ~ # pip show ka-lite
(env)idb-bsf-vagrant-269 ~ # pip show django
(env)idb-bsf-vagrant-269 ~ # pip install ka-lite==0.16.9
(...)
Downloading/unpacking Django>=1.5 (from django-js-reverse==0.5.0->ka-lite==0.16.9)
  Downloading Django-2.0.tar.gz (8.0MB): 8.0MB downloaded
(...)
AttributeError: 'module' object has no attribute 'lru_cache'
```

**Comment by fheslouin** [comment]
So dependency is requiring Django 2.0. I'm not sure it is a good idea to downgrade Django afterward.

**Comment by swbsf** [comment]
Not even, dependency is only requiring Django>=1.5. Therefore pip is installing latest version. So we basically need >= 1.5 and < 2.0. That's what this task is doing, nothing is updated if version already installed is good. 
But I got your point, this issue seems to be on ka-lite side. In the meantime this fix would be a dirty trick avoiding installation failure on all new devices. Let put it plainly, as for today, we can **not** install new devices with Ka-lite on.

**Comment by benjaoming** [comment]
Hi! I'm a KA Lite dev.

It is true that there is a Django dependency in KA Lite, actually it got pinned to avoid the confusion of downloading another version than what is bundled and make it predictable so it could be deleted afterwards. Yes, we never managed to unbundle an ancient version of Django because customizations to its codebase made it complicated.

In 0.16.x, the bundled Django is located here:

https://github.com/learningequality/ka-lite/tree/0.16.x/python-packages/django

We moved it in 0.17.x and introduced a script that deletes the auto-downloaded version when populating dependencies in `ka-lite-static`:

https://github.com/learningequality/ka-lite/tree/0.17.x/kalite/packages/bundled/django

Downloaded dependency django 1.5.12 gets deleted when building `ka-lite-static` here:

https://github.com/learningequality/ka-lite/commit/2e67b5afce2c395fd5974e8ae299132fb7188a76#diff-2eeaed663bd0d25b7e608891384b7298R255

**Summary: Use `ka-lite-static`, it doesn't have dependencies because it bundles everything.**

Background: `ka-lite` with dynamic dependencies was planned at a time when we wanted to have a maintained version of KA Lite compatible with the latest versions of Django, so to make KA Lite integrate better with other projects.. etc. This still hasn't happened because the source code modifications in the bundled Django blocks us from replacing it with a vanilla Django.

**Pull request merged**
