### PR TITLE
Remove the uwsgi role, add a cleanup role.

### LINKED ISSUE #25: Remove the /etc/systemd/system/uwsgi.service file
This just isn't needed.

We should stop adding it in ansiblecube, and **remove it from the boxes that already have it**.

### PR DESCRIPTION
**Pull request by letompouce**
uwsgi is now completely handled by the ideascube package postinstall
script. Let's remove the uwsgi role completely.

Add a cleanup role that will remove the files installed by the uwsgi role.
This role will be used as a rolling release role, cleaning up the stuff
we left behind us after such changes.

Fixes #25.

### CODE REVIEW

**Comment by fheslouin** [comment]
It won't work in one use case. If we want to use the mook application without Ideascube...
It should not happen so often, but we should keep it in mind.

**Comment by letompouce** [comment]
Would mongodb cry because it wants to start before an uwsgi service that doesn't exist?

**Comment by fheslouin** [comment]
No it won't cry. However if a webapp is run by a uwsgi service and need access to a mongoDB service. Uwsgi has to be started after mongoDB

**Comment by fheslouin** [comment]
The PR #102 is taking care of these change adapted to `oneUpdateFile` branch

**Pull request closed without merging**
